name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust@v1

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Build
      run: RUSTFLAGS='-D warnings' cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
